---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      requests:
        memory: "64Mi"  # Minimum guaranteed memory
        cpu: "250m"     # Minimum guaranteed CPU
      limits:
        memory: "128Mi" # Maximum memory
        cpu: "500m"     # Maximum CPU
    ports:
      - containerPort: 80
